{% set name = "penaltymodel-lp" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/penaltymodel-lp-{{ version }}.tar.gz
    sha256: 5203d6d9af3efebd0744ac984dd367fb8eb48fe5afb060b6c2273d5b62dac101
  - url: https://raw.githubusercontent.com/dwavesystems/penaltymodel/lp-{{ version }}/LICENSE
    sha256: 100ca5aff29fe3d7bcc94e59dfcf0fd55d93745fc590c87f217a99fd314f0884

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dimod >=0.8.0,<0.11.0
    - numpy >=1.19.1,<2.0.0
    - penaltymodel >=0.16.0,<0.17.0
    - python >={{ python_min }}
    - scipy >=1.5.2,<2.0.0

test:
  imports:
    - penaltymodel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/penaltymodel
  summary: Generates penalty models using SciPy's linear programming.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
